import Head from 'next/head'

import {useSession, signIn, signOut} from "next-auth/react"


export default function Home() {
  const {data: session} = useSession()



  return (
    <dev>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {!session ? <button onClick={() => signIn("spotify")}>signIn</button> : <button onClick={() => signOut()}>signOut</button>}
      </main>

      <footer >
        
      </footer>
    </dev>
  )
}
